<?php namespace goliatone\flatg\config\drivers {


    class PhpConfigDriver extends AbstractConfigDriver
    {
        /**
         * Imports a config file and makes
         * content available for a Config
         * instance.
         *
         * @param  string $file File path
         * @return array Configuration object
         */
        public function import($file)
        {
            return include($file);
        }

        public function load($content)
        {
            return $content;
        }

        /**
         * Formats and saves a configuration
         * object.
         *
         * @param array $data Configuration object
         * @return string
         */
        public function format($content)
        {
            $config = var_export($content, TRUE);

            $formatted = str_replace(
                array('  ', 'array ('),
                array("\t", 'array('),
                $config
            );

            $output = <<<CONF
<?php
/* FILE AUTOGENERATED BY
 * goliatone\flatg\config\Config
 */
return {$formatted};
CONF;
            return $output;
        }

    }
}